-- Ajuste catálogos: Moneda, nombres UTF-8, ciudades Venezuela
-- Ejecutar: sqlcmd -S SERVIDOR -d TrebolDB -E -i 30_AjustePaisesCiudadMonedaUtf8.sql -f 65001
USE TrebolDB;
GO
SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
GO

/* Quitar coordenadas; agregar Moneda */
IF COL_LENGTH('Pais', 'Moneda') IS NULL
    ALTER TABLE Pais ADD Moneda NVARCHAR(3) NULL;
GO
IF COL_LENGTH('Pais', 'Longitud') IS NOT NULL
BEGIN
    DECLARE @sqlDrop NVARCHAR(MAX) = N'';
    SELECT @sqlDrop = @sqlDrop + N'ALTER TABLE Pais DROP CONSTRAINT ' + QUOTENAME(dc.name) + N';'
    FROM sys.default_constraints dc
    JOIN sys.columns c ON c.default_object_id = dc.object_id
    WHERE dc.parent_object_id = OBJECT_ID(N'Pais') AND c.name IN (N'Longitud', N'Latitud');
    IF LEN(@sqlDrop) > 0 EXEC sp_executesql @sqlDrop;
    ALTER TABLE Pais DROP COLUMN Longitud;
    ALTER TABLE Pais DROP COLUMN Latitud;
END
GO

/* Moneda por código ISO */
UPDATE p SET Moneda = m.Moneda
FROM Pais p
JOIN (VALUES
    (N'AD', N'EUR'),
    (N'AE', N'AED'),
    (N'AF', N'AFN'),
    (N'AG', N'XCD'),
    (N'AI', N'XCD'),
    (N'AL', N'ALL'),
    (N'AM', N'AMD'),
    (N'AO', N'AOA'),
    (N'AR', N'ARS'),
    (N'AS', N'USD'),
    (N'AT', N'EUR'),
    (N'AU', N'AUD'),
    (N'AW', N'AWG'),
    (N'AZ', N'AZN'),
    (N'BA', N'BAM'),
    (N'BB', N'BBD'),
    (N'BD', N'BDT'),
    (N'BE', N'EUR'),
    (N'BF', N'XOF'),
    (N'BG', N'BGN'),
    (N'BH', N'BHD'),
    (N'BI', N'BIF'),
    (N'BJ', N'XOF'),
    (N'BM', N'BMD'),
    (N'BN', N'BND'),
    (N'BO', N'BOB'),
    (N'BR', N'BRL'),
    (N'BS', N'BSD'),
    (N'BT', N'BTN'),
    (N'BW', N'BWP'),
    (N'BY', N'BYN'),
    (N'BZ', N'BZD'),
    (N'CA', N'CAD'),
    (N'CC', N'AUD'),
    (N'CD', N'CDF'),
    (N'CF', N'XAF'),
    (N'CG', N'XAF'),
    (N'CH', N'CHF'),
    (N'CI', N'XOF'),
    (N'CK', N'NZD'),
    (N'CL', N'CLP'),
    (N'CM', N'XAF'),
    (N'CN', N'CNY'),
    (N'CO', N'COP'),
    (N'CR', N'CRC'),
    (N'CU', N'CUP'),
    (N'CV', N'CVE'),
    (N'CX', N'AUD'),
    (N'CY', N'EUR'),
    (N'CZ', N'CZK'),
    (N'DE', N'EUR'),
    (N'DJ', N'DJF'),
    (N'DK', N'DKK'),
    (N'DM', N'XCD'),
    (N'DO', N'DOP'),
    (N'DZ', N'DZD'),
    (N'EC', N'USD'),
    (N'EE', N'EUR'),
    (N'EG', N'EGP'),
    (N'EL', N'EUR'),
    (N'ER', N'ERN'),
    (N'ES', N'EUR'),
    (N'ET', N'ETB'),
    (N'FI', N'EUR'),
    (N'FJ', N'FJD'),
    (N'FK', N'FKP'),
    (N'FM', N'USD'),
    (N'FO', N'DKK'),
    (N'FR', N'EUR'),
    (N'GA', N'XAF'),
    (N'GB', N'GBP'),
    (N'GD', N'XCD'),
    (N'GE', N'GEL'),
    (N'GG', N'GBP'),
    (N'GH', N'GHS'),
    (N'GI', N'GIP'),
    (N'GL', N'DKK'),
    (N'GM', N'GMD'),
    (N'GN', N'GNF'),
    (N'GP', N'EUR'),
    (N'GQ', N'XAF'),
    (N'GS', N'GBP'),
    (N'GT', N'GTQ'),
    (N'GU', N'USD'),
    (N'GW', N'XOF'),
    (N'GY', N'GYD'),
    (N'HK', N'HKD'),
    (N'HM', N'USD'),
    (N'HN', N'HNL'),
    (N'HR', N'EUR'),
    (N'HT', N'HTG'),
    (N'HU', N'HUF'),
    (N'ID', N'IDR'),
    (N'IE', N'EUR'),
    (N'IL', N'ILS'),
    (N'IM', N'GBP'),
    (N'IN', N'INR'),
    (N'IO', N'USD'),
    (N'IQ', N'IQD'),
    (N'IR', N'IRR'),
    (N'IS', N'ISK'),
    (N'IT', N'EUR'),
    (N'JE', N'GBP'),
    (N'JM', N'JMD'),
    (N'JO', N'JOD'),
    (N'JP', N'JPY'),
    (N'KE', N'KES'),
    (N'KG', N'KGS'),
    (N'KH', N'KHR'),
    (N'KI', N'AUD'),
    (N'KM', N'KMF'),
    (N'KN', N'XCD'),
    (N'KP', N'KPW'),
    (N'KR', N'KRW'),
    (N'KW', N'KWD'),
    (N'KY', N'KYD'),
    (N'KZ', N'KZT'),
    (N'LA', N'LAK'),
    (N'LB', N'LBP'),
    (N'LC', N'XCD'),
    (N'LI', N'CHF'),
    (N'LK', N'LKR'),
    (N'LR', N'LRD'),
    (N'LS', N'LSL'),
    (N'LT', N'EUR'),
    (N'LU', N'EUR'),
    (N'LV', N'EUR'),
    (N'LY', N'LYD'),
    (N'MA', N'MAD'),
    (N'MC', N'EUR'),
    (N'MD', N'MDL'),
    (N'ME', N'EUR'),
    (N'MG', N'MGA'),
    (N'MH', N'USD'),
    (N'MK', N'MKD'),
    (N'ML', N'XOF'),
    (N'MM', N'MMK'),
    (N'MN', N'MNT'),
    (N'MO', N'MOP'),
    (N'MP', N'USD'),
    (N'MQ', N'EUR'),
    (N'MR', N'MRU'),
    (N'MS', N'XCD'),
    (N'MT', N'EUR'),
    (N'MU', N'MUR'),
    (N'MV', N'MVR'),
    (N'MW', N'MWK'),
    (N'MX', N'MXN'),
    (N'MY', N'MYR'),
    (N'MZ', N'MZN'),
    (N'NA', N'NAD'),
    (N'NC', N'XPF'),
    (N'NE', N'XOF'),
    (N'NF', N'AUD'),
    (N'NG', N'NGN'),
    (N'NI', N'NIO'),
    (N'NL', N'EUR'),
    (N'NO', N'NOK'),
    (N'NP', N'NPR'),
    (N'NR', N'AUD'),
    (N'NU', N'NZD'),
    (N'NZ', N'NZD'),
    (N'OM', N'OMR'),
    (N'PA', N'PAB'),
    (N'PE', N'PEN'),
    (N'PF', N'XPF'),
    (N'PG', N'PGK'),
    (N'PH', N'PHP'),
    (N'PK', N'PKR'),
    (N'PL', N'PLN'),
    (N'PM', N'EUR'),
    (N'PN', N'NZD'),
    (N'PR', N'USD'),
    (N'PS', N'ILS'),
    (N'PT', N'EUR'),
    (N'PW', N'USD'),
    (N'PY', N'PYG'),
    (N'QA', N'QAR'),
    (N'RE', N'EUR'),
    (N'RO', N'RON'),
    (N'RS', N'RSD'),
    (N'RU', N'RUB'),
    (N'RW', N'RWF'),
    (N'SA', N'SAR'),
    (N'SB', N'SBD'),
    (N'SC', N'SCR'),
    (N'SD', N'SDG'),
    (N'SE', N'SEK'),
    (N'SG', N'SGD'),
    (N'SH', N'SHP'),
    (N'SI', N'EUR'),
    (N'SJ', N'USD'),
    (N'SK', N'EUR'),
    (N'SL', N'SLE'),
    (N'SM', N'EUR'),
    (N'SN', N'XOF'),
    (N'SO', N'SOS'),
    (N'SR', N'SRD'),
    (N'ST', N'STN'),
    (N'SV', N'USD'),
    (N'SY', N'SYP'),
    (N'SZ', N'SZL'),
    (N'TC', N'USD'),
    (N'TD', N'XAF'),
    (N'TF', N'USD'),
    (N'TG', N'XOF'),
    (N'TH', N'THB'),
    (N'TK', N'NZD'),
    (N'TL', N'USD'),
    (N'TM', N'TMT'),
    (N'TN', N'TND'),
    (N'TO', N'TOP'),
    (N'TR', N'TRY'),
    (N'TT', N'TTD'),
    (N'TW', N'TWD'),
    (N'TZ', N'TZS'),
    (N'UA', N'UAH'),
    (N'UG', N'UGX'),
    (N'US', N'USD'),
    (N'UY', N'UYU'),
    (N'UZ', N'UZS'),
    (N'VA', N'EUR'),
    (N'VC', N'XCD'),
    (N'VE', N'VES'),
    (N'VG', N'USD'),
    (N'VI', N'USD'),
    (N'VN', N'VND'),
    (N'VU', N'VUV'),
    (N'WF', N'XPF'),
    (N'WS', N'WST'),
    (N'YE', N'YER'),
    (N'YT', N'EUR'),
    (N'ZA', N'ZAR'),
    (N'ZM', N'ZMW'),
    (N'ZW', N'ZWL')
) AS m(Codigo, Moneda) ON m.Codigo = p.Codigo;
GO

ALTER TABLE Pais ALTER COLUMN Moneda NVARCHAR(3) NOT NULL;
GO

/* Nombres de países en español (donde aplica) */
UPDATE p SET Nombre = n.Nombre
FROM Pais p
JOIN (VALUES
    (N'AE', N'Emiratos Árabes Unidos'),
    (N'AR', N'Argentina'),
    (N'AT', N'Austria'),
    (N'AU', N'Australia'),
    (N'BE', N'Bélgica'),
    (N'BO', N'Bolivia'),
    (N'BR', N'Brasil'),
    (N'CA', N'Canadá'),
    (N'CH', N'Suiza'),
    (N'CI', N'Costa de Marfil'),
    (N'CL', N'Chile'),
    (N'CN', N'China'),
    (N'CO', N'Colombia'),
    (N'CR', N'Costa Rica'),
    (N'CU', N'Cuba'),
    (N'DE', N'Alemania'),
    (N'DK', N'Dinamarca'),
    (N'DO', N'República Dominicana'),
    (N'EC', N'Ecuador'),
    (N'EG', N'Egipto'),
    (N'ES', N'España'),
    (N'FI', N'Finlandia'),
    (N'FR', N'Francia'),
    (N'GB', N'Reino Unido'),
    (N'GR', N'Grecia'),
    (N'GT', N'Guatemala'),
    (N'HN', N'Honduras'),
    (N'ID', N'Indonesia'),
    (N'IE', N'Irlanda'),
    (N'IL', N'Israel'),
    (N'IN', N'India'),
    (N'IT', N'Italia'),
    (N'JP', N'Japón'),
    (N'KP', N'Corea del Norte'),
    (N'KR', N'Corea del Sur'),
    (N'MA', N'Marruecos'),
    (N'MX', N'México'),
    (N'MY', N'Malasia'),
    (N'NI', N'Nicaragua'),
    (N'NL', N'Países Bajos'),
    (N'NO', N'Noruega'),
    (N'NZ', N'Nueva Zelanda'),
    (N'PA', N'Panamá'),
    (N'PE', N'Perú'),
    (N'PH', N'Filipinas'),
    (N'PL', N'Polonia'),
    (N'PT', N'Portugal'),
    (N'PY', N'Paraguay'),
    (N'RU', N'Rusia'),
    (N'SA', N'Arabia Saudita'),
    (N'SE', N'Suecia'),
    (N'SG', N'Singapur'),
    (N'SV', N'El Salvador'),
    (N'TH', N'Tailandia'),
    (N'TR', N'Turquía'),
    (N'UK', N'Reino Unido'),
    (N'US', N'Estados Unidos'),
    (N'UY', N'Uruguay'),
    (N'VE', N'Venezuela'),
    (N'VN', N'Vietnam'),
    (N'ZA', N'Sudáfrica')
) AS n(Codigo, Nombre) ON n.Codigo = p.Codigo;
GO

/* Ciudades Colombia: tildes faltantes */
UPDATE Ciudad SET Nombre = N'Bogotá'
WHERE PaisId = (SELECT PaisId FROM Pais WHERE Codigo = N'CO') AND Nombre = N'Bogota';
GO

/* Colombia: conservar variante con tilde cuando hay duplicado CI_AI */
DECLARE @PaisCo INT = (SELECT PaisId FROM Pais WHERE Codigo = N'CO');
IF OBJECT_ID('tempdb..#CiudadCanon') IS NOT NULL DROP TABLE #CiudadCanon;
SELECT CiudadId, CanonId
INTO #CiudadCanon
FROM (
    SELECT c.CiudadId,
           FIRST_VALUE(c.CiudadId) OVER (
               PARTITION BY c.PaisId, c.Nombre COLLATE Latin1_General_CI_AI
               ORDER BY LEN(c.Nombre) DESC, c.CiudadId
           ) AS CanonId
    FROM Ciudad c
    WHERE c.PaisId = @PaisCo
) x
WHERE CiudadId <> CanonId;
GO

UPDATE p SET CiudadId = m.CanonId
FROM Profesional p
JOIN #CiudadCanon m ON m.CiudadId = p.CiudadId;
UPDATE u SET CiudadId = m.CanonId
FROM Usuario u
JOIN #CiudadCanon m ON m.CiudadId = u.CiudadId;
DELETE c FROM Ciudad c JOIN #CiudadCanon m ON m.CiudadId = c.CiudadId;
GO

/* Colombia: unificar duplicados sin tilde cuando existe versión acentuada */
DECLARE @PaisCo INT = (SELECT PaisId FROM Pais WHERE Codigo = N'CO');
UPDATE p SET CiudadId = ca.CiudadId
FROM Profesional p
JOIN Ciudad c ON c.CiudadId = p.CiudadId
JOIN Ciudad ca ON ca.PaisId = c.PaisId
    AND ca.CiudadId <> c.CiudadId
    AND ca.Nombre COLLATE Latin1_General_CI_AI = c.Nombre COLLATE Latin1_General_CI_AI
    AND ca.Nombre LIKE N'%[áéíóúñÁÉÍÓÚÑ]%'
WHERE c.PaisId = @PaisCo
  AND c.Nombre NOT LIKE N'%[áéíóúñÁÉÍÓÚÑ]%';

UPDATE u SET CiudadId = ca.CiudadId
FROM Usuario u
JOIN Ciudad c ON c.CiudadId = u.CiudadId
JOIN Ciudad ca ON ca.PaisId = c.PaisId
    AND ca.CiudadId <> c.CiudadId
    AND ca.Nombre COLLATE Latin1_General_CI_AI = c.Nombre COLLATE Latin1_General_CI_AI
    AND ca.Nombre LIKE N'%[áéíóúñÁÉÍÓÚÑ]%'
WHERE c.PaisId = @PaisCo
  AND c.Nombre NOT LIKE N'%[áéíóúñÁÉÍÓÚÑ]%';

DELETE c
FROM Ciudad c
WHERE c.PaisId = @PaisCo
  AND c.Nombre NOT LIKE N'%[áéíóúñÁÉÍÓÚÑ]%'
  AND EXISTS (
      SELECT 1 FROM Ciudad ca
      WHERE ca.PaisId = c.PaisId
        AND ca.CiudadId <> c.CiudadId
        AND ca.Nombre COLLATE Latin1_General_CI_AI = c.Nombre COLLATE Latin1_General_CI_AI
        AND ca.Nombre LIKE N'%[áéíóúñÁÉÍÓÚÑ]%'
  );
GO

/* Ciudades Venezuela */
DECLARE @PaisVe INT = (SELECT PaisId FROM Pais WHERE Codigo = N'VE');
IF @PaisVe IS NOT NULL AND NOT EXISTS (SELECT 1 FROM Ciudad WHERE PaisId = @PaisVe)
BEGIN
    INSERT INTO Ciudad (PaisId, Nombre, Estado) VALUES
        (@PaisVe, N'Abejales', 1),
        (@PaisVe, N'Acarigua', 1),
        (@PaisVe, N'Acevedo', 1),
        (@PaisVe, N'Achaguas', 1),
        (@PaisVe, N'Acosta', 1),
        (@PaisVe, N'Adícora', 1),
        (@PaisVe, N'Agua Blanca', 1),
        (@PaisVe, N'Aguada Grande', 1),
        (@PaisVe, N'Aguasay', 1),
        (@PaisVe, N'Aguirre', 1),
        (@PaisVe, N'Alberto Adriani', 1),
        (@PaisVe, N'Alberto Arvelo Torrealba', 1),
        (@PaisVe, N'Almirante Padilla', 1),
        (@PaisVe, N'Altagracia', 1),
        (@PaisVe, N'Altagracia de Orituco', 1),
        (@PaisVe, N'Alto Orinoco', 1),
        (@PaisVe, N'Altos de Sucre', 1),
        (@PaisVe, N'Anaco', 1),
        (@PaisVe, N'Andrés Bello', 1),
        (@PaisVe, N'Andrés Eloy Blanco', 1),
        (@PaisVe, N'Andrés Mata', 1),
        (@PaisVe, N'Angostura (Raúl Leoni)', 1),
        (@PaisVe, N'Antolín del Campo', 1),
        (@PaisVe, N'Antonio Díaz', 1),
        (@PaisVe, N'Antonio José de Sucre', 1),
        (@PaisVe, N'Antonio Pinto Salinas', 1),
        (@PaisVe, N'Antonio Rómulo Costa', 1),
        (@PaisVe, N'Anzoátegui', 1),
        (@PaisVe, N'Apartaderos Cojedes', 1),
        (@PaisVe, N'Apartaderos Mérida', 1),
        (@PaisVe, N'Aragua', 1),
        (@PaisVe, N'Aragua de Barcelona', 1),
        (@PaisVe, N'Aragua de Maturín', 1),
        (@PaisVe, N'Araguita', 1),
        (@PaisVe, N'Arapuey', 1),
        (@PaisVe, N'Araure', 1),
        (@PaisVe, N'Araya', 1),
        (@PaisVe, N'Archipiélago Las Aves', 1),
        (@PaisVe, N'Archipiélago Los Monjes', 1),
        (@PaisVe, N'Archipiélago Los Roques', 1),
        (@PaisVe, N'Aricagua', 1),
        (@PaisVe, N'Arismendi', 1),
        (@PaisVe, N'Aroa', 1),
        (@PaisVe, N'Arzobispo Chacón', 1),
        (@PaisVe, N'Arístides Bastidas', 1),
        (@PaisVe, N'Atabapo', 1),
        (@PaisVe, N'Atanasio Girardot', 1),
        (@PaisVe, N'Atarigua', 1),
        (@PaisVe, N'Atures', 1),
        (@PaisVe, N'Autana', 1),
        (@PaisVe, N'Ayacucho', 1),
        (@PaisVe, N'Bachaquero', 1),
        (@PaisVe, N'Bailadores', 1),
        (@PaisVe, N'Baralt', 1),
        (@PaisVe, N'Barbacoas', 1),
        (@PaisVe, N'Barcelona', 1),
        (@PaisVe, N'Barinas', 1),
        (@PaisVe, N'Barinitas', 1),
        (@PaisVe, N'Barquisimeto', 1),
        (@PaisVe, N'Barrancas', 1),
        (@PaisVe, N'Barrancas del Orinoco', 1),
        (@PaisVe, N'Baruta', 1),
        (@PaisVe, N'Batatal', 1),
        (@PaisVe, N'Bejuma', 1),
        (@PaisVe, N'Belén', 1),
        (@PaisVe, N'Benítez', 1),
        (@PaisVe, N'Bermúdez', 1),
        (@PaisVe, N'Betijoque', 1),
        (@PaisVe, N'Biruaca', 1),
        (@PaisVe, N'Biscucuy', 1),
        (@PaisVe, N'Bobare', 1),
        (@PaisVe, N'Bobures', 1),
        (@PaisVe, N'Boca de Aroa', 1),
        (@PaisVe, N'Boca de Pozo', 1),
        (@PaisVe, N'Boca de Río', 1),
        (@PaisVe, N'Boca de Uchire', 1),
        (@PaisVe, N'Boconoito', 1),
        (@PaisVe, N'Boconó', 1),
        (@PaisVe, N'Bolívar', 1),
        (@PaisVe, N'Boraure', 1),
        (@PaisVe, N'Borota', 1),
        (@PaisVe, N'Bramon', 1),
        (@PaisVe, N'Brión', 1),
        (@PaisVe, N'Bruzual', 1),
        (@PaisVe, N'Buchivacoa', 1),
        (@PaisVe, N'Buroz', 1),
        (@PaisVe, N'Cabimas', 1),
        (@PaisVe, N'Cabruta', 1),
        (@PaisVe, N'Cabudare', 1),
        (@PaisVe, N'Cabure', 1),
        (@PaisVe, N'Cacique Manaure', 1),
        (@PaisVe, N'Cagua', 1),
        (@PaisVe, N'Caicara de Maturín', 1),
        (@PaisVe, N'Caicara del Orinoco', 1),
        (@PaisVe, N'Caja Seca', 1),
        (@PaisVe, N'Cajigal', 1),
        (@PaisVe, N'Calabozo', 1),
        (@PaisVe, N'Calderas', 1),
        (@PaisVe, N'Camaguán', 1),
        (@PaisVe, N'Camatagua', 1),
        (@PaisVe, N'Campo Concepción', 1),
        (@PaisVe, N'Campo Elías', 1),
        (@PaisVe, N'Campo Elías de Yaracuy', 1),
        (@PaisVe, N'Campo Mara', 1),
        (@PaisVe, N'Campo Rojo', 1),
        (@PaisVe, N'Campo de Carabobo', 1),
        (@PaisVe, N'Camuriquito', 1),
        (@PaisVe, N'Canaguá', 1),
        (@PaisVe, N'Canaima', 1),
        (@PaisVe, N'Candelaria', 1),
        (@PaisVe, N'Canoabo', 1),
        (@PaisVe, N'Cantaura', 1),
        (@PaisVe, N'Capacho', 1),
        (@PaisVe, N'Capadare', 1),
        (@PaisVe, N'Capatárida', 1),
        (@PaisVe, N'Capitanejo', 1),
        (@PaisVe, N'Caracas', 1),
        (@PaisVe, N'Caracciolo Parra Olmedo', 1),
        (@PaisVe, N'Carache', 1),
        (@PaisVe, N'Carayaca', 1),
        (@PaisVe, N'Cardenal Quintero', 1),
        (@PaisVe, N'Cariaco', 1),
        (@PaisVe, N'Caripe', 1),
        (@PaisVe, N'Caripito', 1),
        (@PaisVe, N'Carirubana', 1),
        (@PaisVe, N'Carlos Arvelo', 1),
        (@PaisVe, N'Caroní', 1),
        (@PaisVe, N'Carora', 1),
        (@PaisVe, N'Carrasquero', 1),
        (@PaisVe, N'Carrizal', 1),
        (@PaisVe, N'Carúpano', 1),
        (@PaisVe, N'Casacoima', 1),
        (@PaisVe, N'Casanay', 1),
        (@PaisVe, N'Casigua', 1),
        (@PaisVe, N'Catatumbo', 1),
        (@PaisVe, N'Catia La Mar', 1),
        (@PaisVe, N'Caucagua', 1),
        (@PaisVe, N'Cedeño', 1),
        (@PaisVe, N'Central Tacarigua', 1),
        (@PaisVe, N'Chabasquén', 1),
        (@PaisVe, N'Chacao', 1),
        (@PaisVe, N'Chachopo', 1),
        (@PaisVe, N'Chaguaramal', 1),
        (@PaisVe, N'Chaguaramas', 1),
        (@PaisVe, N'Chaguaramas Guárico', 1),
        (@PaisVe, N'Chaguaramas Miranda', 1),
        (@PaisVe, N'Chaguaramas Monagas', 1),
        (@PaisVe, N'Charallave', 1),
        (@PaisVe, N'Chejende', 1),
        (@PaisVe, N'Chichiriviche', 1),
        (@PaisVe, N'Chiguara', 1),
        (@PaisVe, N'Chiquinquirá', 1),
        (@PaisVe, N'Chirgua', 1),
        (@PaisVe, N'Chirimena', 1),
        (@PaisVe, N'Chivacoa', 1),
        (@PaisVe, N'Choroní', 1),
        (@PaisVe, N'Churuguara', 1),
        (@PaisVe, N'Chuspa', 1),
        (@PaisVe, N'Ciudad Alianza', 1),
        (@PaisVe, N'Ciudad Bolivia', 1),
        (@PaisVe, N'Ciudad Bolívar', 1),
        (@PaisVe, N'Ciudad Ojeda', 1),
        (@PaisVe, N'Ciudad Piar', 1),
        (@PaisVe, N'Clarines', 1),
        (@PaisVe, N'Cocorote', 1),
        (@PaisVe, N'Colina', 1),
        (@PaisVe, N'Coloncito', 1),
        (@PaisVe, N'Colonia Tovar', 1),
        (@PaisVe, N'Colón', 1),
        (@PaisVe, N'Cordero', 1),
        (@PaisVe, N'Coro', 1),
        (@PaisVe, N'Crespo', 1),
        (@PaisVe, N'Cristóbal Rojas', 1),
        (@PaisVe, N'Cruz Paredes', 1),
        (@PaisVe, N'Cruz Salmerón Acosta', 1),
        (@PaisVe, N'Cubiro', 1),
        (@PaisVe, N'Cuicas', 1),
        (@PaisVe, N'Cují', 1),
        (@PaisVe, N'Cumanacoa', 1),
        (@PaisVe, N'Cumaná', 1),
        (@PaisVe, N'Cumarebo', 1),
        (@PaisVe, N'Cupira', 1),
        (@PaisVe, N'Curiepe', 1),
        (@PaisVe, N'Cárdenas', 1),
        (@PaisVe, N'Córdoba', 1),
        (@PaisVe, N'Cúa', 1),
        (@PaisVe, N'Dabajuro', 1),
        (@PaisVe, N'Democracia', 1),
        (@PaisVe, N'Diego Bautista Urbaneja', 1),
        (@PaisVe, N'Diego Ibarra', 1),
        (@PaisVe, N'Duaca', 1),
        (@PaisVe, N'Díaz', 1),
        (@PaisVe, N'Ejido', 1),
        (@PaisVe, N'El Amparo', 1),
        (@PaisVe, N'El Batey', 1),
        (@PaisVe, N'El Baúl', 1),
        (@PaisVe, N'El Callao', 1),
        (@PaisVe, N'El Cantón', 1),
        (@PaisVe, N'El Carmelo', 1),
        (@PaisVe, N'El Chaparro', 1),
        (@PaisVe, N'El Chivo', 1),
        (@PaisVe, N'El Cobre', 1),
        (@PaisVe, N'El Consejo', 1),
        (@PaisVe, N'El Dividive', 1),
        (@PaisVe, N'El Dorado', 1),
        (@PaisVe, N'El Espinal', 1),
        (@PaisVe, N'El Furrial', 1),
        (@PaisVe, N'El Guapo', 1),
        (@PaisVe, N'El Guayabo', 1),
        (@PaisVe, N'El Hatillo', 1),
        (@PaisVe, N'El Jaguito', 1),
        (@PaisVe, N'El Jarillo', 1),
        (@PaisVe, N'El Junquito', 1),
        (@PaisVe, N'El Limón', 1),
        (@PaisVe, N'El Manteco', 1),
        (@PaisVe, N'El Manzano', 1),
        (@PaisVe, N'El Mene', 1),
        (@PaisVe, N'El Morro Puerto Santo', 1),
        (@PaisVe, N'El Nula', 1),
        (@PaisVe, N'El Palito', 1),
        (@PaisVe, N'El Palmar', 1),
        (@PaisVe, N'El Pao', 1),
        (@PaisVe, N'El Pao Anzoátegui', 1),
        (@PaisVe, N'El Pao Cojedes', 1),
        (@PaisVe, N'El Pilar', 1),
        (@PaisVe, N'El Pinal', 1),
        (@PaisVe, N'El Poblado', 1),
        (@PaisVe, N'El Socorro', 1),
        (@PaisVe, N'El Sombrero', 1),
        (@PaisVe, N'El Tejero', 1),
        (@PaisVe, N'El Tigre', 1),
        (@PaisVe, N'El Tigrito', 1),
        (@PaisVe, N'El Tocuyo', 1),
        (@PaisVe, N'El Valle del Espíritu Santo', 1),
        (@PaisVe, N'El Venado', 1),
        (@PaisVe, N'El Vigía', 1),
        (@PaisVe, N'El Yaque', 1),
        (@PaisVe, N'Elorza', 1),
        (@PaisVe, N'Encontrados', 1),
        (@PaisVe, N'Escuque', 1),
        (@PaisVe, N'Esteller', 1),
        (@PaisVe, N'Ezequiel Zamora', 1),
        (@PaisVe, N'Falcón', 1),
        (@PaisVe, N'Farriar', 1),
        (@PaisVe, N'Federación', 1),
        (@PaisVe, N'Fernando Peñalver', 1),
        (@PaisVe, N'Fernández Feo', 1),
        (@PaisVe, N'Filas de Mariche', 1),
        (@PaisVe, N'Francisco Del Carmen Carvajal', 1),
        (@PaisVe, N'Francisco Javier Pulgar', 1),
        (@PaisVe, N'Francisco Linares Alcántara', 1),
        (@PaisVe, N'Francisco de Miranda', 1),
        (@PaisVe, N'García', 1),
        (@PaisVe, N'García de Hevia', 1),
        (@PaisVe, N'General Sir Arthur McGregor', 1),
        (@PaisVe, N'Gibraltar', 1),
        (@PaisVe, N'Girardot', 1),
        (@PaisVe, N'Gran Sabana', 1),
        (@PaisVe, N'Guaca', 1),
        (@PaisVe, N'Guacara', 1),
        (@PaisVe, N'Guaicaipuro', 1),
        (@PaisVe, N'Guama', 1),
        (@PaisVe, N'Guanape', 1),
        (@PaisVe, N'Guanare', 1),
        (@PaisVe, N'Guanarito', 1),
        (@PaisVe, N'Guanta', 1),
        (@PaisVe, N'Guaraque', 1),
        (@PaisVe, N'Guarenas', 1),
        (@PaisVe, N'Guaríco', 1),
        (@PaisVe, N'Guasdualito', 1),
        (@PaisVe, N'Guasipati', 1),
        (@PaisVe, N'Guatire', 1),
        (@PaisVe, N'Guigue', 1),
        (@PaisVe, N'Guiria', 1),
        (@PaisVe, N'Guri', 1),
        (@PaisVe, N'Guásimos', 1),
        (@PaisVe, N'Gómez', 1),
        (@PaisVe, N'Heres', 1),
        (@PaisVe, N'Higuerote', 1),
        (@PaisVe, N'Humocaro Alto', 1),
        (@PaisVe, N'Humocaro Bajo', 1),
        (@PaisVe, N'Independencia', 1),
        (@PaisVe, N'Irapa', 1),
        (@PaisVe, N'Iribarren', 1),
        (@PaisVe, N'Isla La Blanquilla', 1),
        (@PaisVe, N'Isla La Orchila', 1),
        (@PaisVe, N'Isla La Sola', 1),
        (@PaisVe, N'Isla La Tortuga y Cayos adyacentes', 1),
        (@PaisVe, N'Isla de Aves', 1),
        (@PaisVe, N'Isla de Patos', 1),
        (@PaisVe, N'Isla de Toas', 1),
        (@PaisVe, N'Islas Los Frailes', 1),
        (@PaisVe, N'Islas Los Hermanos', 1),
        (@PaisVe, N'Islas Los Testigos', 1),
        (@PaisVe, N'Isnotú', 1),
        (@PaisVe, N'Jacura', 1),
        (@PaisVe, N'Jajó', 1),
        (@PaisVe, N'Jesús Enrique Losada', 1),
        (@PaisVe, N'Jesús María Semprún', 1),
        (@PaisVe, N'Jiménez', 1),
        (@PaisVe, N'José Antonio Páez', 1),
        (@PaisVe, N'José Felipe Márquez Cañizalez', 1),
        (@PaisVe, N'José Félix Ribas', 1),
        (@PaisVe, N'José Gregorio Monagas', 1),
        (@PaisVe, N'José Joaquín Veroes', 1),
        (@PaisVe, N'José Laurencio Silva', 1),
        (@PaisVe, N'José María Vargas', 1),
        (@PaisVe, N'José Rafael Revenga', 1),
        (@PaisVe, N'José Tadeo Monagas', 1),
        (@PaisVe, N'José Ángel Lamas', 1),
        (@PaisVe, N'Juan Antonio Sotillo', 1),
        (@PaisVe, N'Juan Germán Roscio', 1),
        (@PaisVe, N'Juan José Mora', 1),
        (@PaisVe, N'Juan Manuel Cajigal', 1),
        (@PaisVe, N'Juan Vicente Campos Elías', 1),
        (@PaisVe, N'Juangriego', 1),
        (@PaisVe, N'Judibana', 1),
        (@PaisVe, N'Julio César Salas', 1),
        (@PaisVe, N'Julián Mellado', 1),
        (@PaisVe, N'Junín', 1),
        (@PaisVe, N'Jusepín', 1),
        (@PaisVe, N'Justo Briceño', 1),
        (@PaisVe, N'Jáuregui', 1),
        (@PaisVe, N'La Aguadita', 1),
        (@PaisVe, N'La Aparición', 1),
        (@PaisVe, N'La Asunción', 1),
        (@PaisVe, N'La Azulita', 1),
        (@PaisVe, N'La Cañada de Urdaneta', 1),
        (@PaisVe, N'La Ceiba', 1),
        (@PaisVe, N'La Concepción de Trujllo', 1),
        (@PaisVe, N'La Concepción del Zulia', 1),
        (@PaisVe, N'La Cruz de Taratara', 1),
        (@PaisVe, N'La Fría', 1),
        (@PaisVe, N'La Grita', 1),
        (@PaisVe, N'La Guaira', 1),
        (@PaisVe, N'La Guardia', 1),
        (@PaisVe, N'La Mesa de Esnujaque', 1),
        (@PaisVe, N'La Miel', 1),
        (@PaisVe, N'La Misión', 1),
        (@PaisVe, N'La Paragua', 1),
        (@PaisVe, N'La Paz', 1),
        (@PaisVe, N'La Pedrera', 1),
        (@PaisVe, N'La Playa', 1),
        (@PaisVe, N'La Puerta', 1),
        (@PaisVe, N'La Quebrada', 1),
        (@PaisVe, N'La Sierrita', 1),
        (@PaisVe, N'La Tendida', 1),
        (@PaisVe, N'La Toscana', 1),
        (@PaisVe, N'La Trinidad', 1),
        (@PaisVe, N'La Vela de Coro', 1),
        (@PaisVe, N'La Victoria', 1),
        (@PaisVe, N'Lagunillas', 1),
        (@PaisVe, N'Lagunillas Mérida', 1),
        (@PaisVe, N'Lagunillas del Zulia', 1),
        (@PaisVe, N'Lander', 1),
        (@PaisVe, N'Las Delicias', 1),
        (@PaisVe, N'Las Hernández', 1),
        (@PaisVe, N'Las Mercedes', 1),
        (@PaisVe, N'Las Mercedes de Los Llanos', 1),
        (@PaisVe, N'Las Piedras de Perijá', 1),
        (@PaisVe, N'Las Tejerías', 1),
        (@PaisVe, N'Las Trincheras', 1),
        (@PaisVe, N'Las Vegas', 1),
        (@PaisVe, N'Las Veguitas', 1),
        (@PaisVe, N'Lechería', 1),
        (@PaisVe, N'Leonardo Infante', 1),
        (@PaisVe, N'Lezama', 1),
        (@PaisVe, N'Libertad', 1),
        (@PaisVe, N'Libertad de Barinas', 1),
        (@PaisVe, N'Libertad de Cojedes', 1),
        (@PaisVe, N'Libertador', 1),
        (@PaisVe, N'Lima Blanco', 1),
        (@PaisVe, N'Litoral', 1),
        (@PaisVe, N'Lobatera', 1),
        (@PaisVe, N'Los Anaucos', 1),
        (@PaisVe, N'Los Cortijos', 1),
        (@PaisVe, N'Los Guayos', 1),
        (@PaisVe, N'Los Salias', 1),
        (@PaisVe, N'Los Taques', 1),
        (@PaisVe, N'Los Teques', 1),
        (@PaisVe, N'Machiques', 1),
        (@PaisVe, N'Machiques de Perijá', 1),
        (@PaisVe, N'Macuto', 1),
        (@PaisVe, N'Magdaleno', 1),
        (@PaisVe, N'Manapiare', 1),
        (@PaisVe, N'Maneiro', 1),
        (@PaisVe, N'Manicuare', 1),
        (@PaisVe, N'Mantecal', 1),
        (@PaisVe, N'Manuel Ezequiel Bruzual', 1),
        (@PaisVe, N'Manuel Monge', 1),
        (@PaisVe, N'Maparari', 1),
        (@PaisVe, N'Mapuey', 1),
        (@PaisVe, N'Mara', 1),
        (@PaisVe, N'Maracaibo', 1),
        (@PaisVe, N'Maracay', 1),
        (@PaisVe, N'Marcano', 1),
        (@PaisVe, N'Mariara', 1),
        (@PaisVe, N'Mariguitar', 1),
        (@PaisVe, N'Mario Briceño Iragorry', 1),
        (@PaisVe, N'Mariño', 1),
        (@PaisVe, N'Maroa', 1),
        (@PaisVe, N'Marín', 1),
        (@PaisVe, N'Matanzas', 1),
        (@PaisVe, N'Maturín', 1),
        (@PaisVe, N'Mauroa', 1),
        (@PaisVe, N'Mejía', 1),
        (@PaisVe, N'Mendoza Fría', 1),
        (@PaisVe, N'Mene Grande', 1),
        (@PaisVe, N'Mene de Mauroa', 1),
        (@PaisVe, N'Mesa de Bolívar', 1),
        (@PaisVe, N'Mesa de Cavacas', 1),
        (@PaisVe, N'Meseta de Chimpire', 1),
        (@PaisVe, N'Michelena', 1),
        (@PaisVe, N'Miraflores', 1),
        (@PaisVe, N'Miranda', 1),
        (@PaisVe, N'Mirimire', 1),
        (@PaisVe, N'Monay', 1),
        (@PaisVe, N'Monseñor Iturriza', 1),
        (@PaisVe, N'Monseñor José Vicente de Unda', 1),
        (@PaisVe, N'Montalbán', 1),
        (@PaisVe, N'Monte Carmelo', 1),
        (@PaisVe, N'Montes', 1),
        (@PaisVe, N'Moroturo', 1),
        (@PaisVe, N'Morán', 1),
        (@PaisVe, N'Morón', 1),
        (@PaisVe, N'Motatán', 1),
        (@PaisVe, N'Mucuchíes', 1),
        (@PaisVe, N'Mucujepe', 1),
        (@PaisVe, N'Mucuruba', 1),
        (@PaisVe, N'Muñóz', 1),
        (@PaisVe, N'Mérida', 1),
        (@PaisVe, N'Naguanagua', 1),
        (@PaisVe, N'Naiguatá', 1),
        (@PaisVe, N'Nirgua', 1),
        (@PaisVe, N'Nueva Bolivia', 1),
        (@PaisVe, N'Obispo Ramos de Lora', 1),
        (@PaisVe, N'Obispos', 1),
        (@PaisVe, N'Ocumare de La Costa', 1),
        (@PaisVe, N'Ocumare de la Costa de Oro', 1),
        (@PaisVe, N'Ocumare del Tuy', 1),
        (@PaisVe, N'Onoto', 1),
        (@PaisVe, N'Ortíz', 1),
        (@PaisVe, N'Ospino', 1),
        (@PaisVe, N'Padre Noguera', 1),
        (@PaisVe, N'Padre Pedro Chien', 1),
        (@PaisVe, N'Palavecino', 1),
        (@PaisVe, N'Palmarejo', 1),
        (@PaisVe, N'Palmarito', 1),
        (@PaisVe, N'Palmasola', 1),
        (@PaisVe, N'Palmira', 1),
        (@PaisVe, N'Palo Negro', 1),
        (@PaisVe, N'Pampanito', 1),
        (@PaisVe, N'Pampatar', 1),
        (@PaisVe, N'Pampán', 1),
        (@PaisVe, N'Panamericano', 1),
        (@PaisVe, N'Panaquire', 1),
        (@PaisVe, N'Pao de San Juan Bautista', 1),
        (@PaisVe, N'Papelón', 1),
        (@PaisVe, N'Paracotos', 1),
        (@PaisVe, N'Paraguaipoa', 1),
        (@PaisVe, N'Pariaguán', 1),
        (@PaisVe, N'Payara', 1),
        (@PaisVe, N'Paz Castillo', 1),
        (@PaisVe, N'Pedernales', 1),
        (@PaisVe, N'Pedraza', 1),
        (@PaisVe, N'Pedregal', 1),
        (@PaisVe, N'Pedro Camejo', 1),
        (@PaisVe, N'Pedro Gual', 1),
        (@PaisVe, N'Pedro María Freites', 1),
        (@PaisVe, N'Pedro María Ureña', 1),
        (@PaisVe, N'Pedro Zaraza', 1),
        (@PaisVe, N'Península de Macanao', 1),
        (@PaisVe, N'Petit', 1),
        (@PaisVe, N'Peña', 1),
        (@PaisVe, N'Piar', 1),
        (@PaisVe, N'Pimpinela', 1),
        (@PaisVe, N'Piñedo', 1),
        (@PaisVe, N'Plaza', 1),
        (@PaisVe, N'Porlamar', 1),
        (@PaisVe, N'Potrerito', 1),
        (@PaisVe, N'Pregonero', 1),
        (@PaisVe, N'Pueblo Llano', 1),
        (@PaisVe, N'Pueblo Nuevo Falcón', 1),
        (@PaisVe, N'Pueblo Nuevo del Zulia', 1),
        (@PaisVe, N'Puerto Ayacucho', 1),
        (@PaisVe, N'Puerto Cabello', 1),
        (@PaisVe, N'Puerto Cumarebo', 1),
        (@PaisVe, N'Puerto Fermín', 1),
        (@PaisVe, N'Puerto La Cruz', 1),
        (@PaisVe, N'Puerto Ordaz', 1),
        (@PaisVe, N'Puerto Páez', 1),
        (@PaisVe, N'Puerto Píritu', 1),
        (@PaisVe, N'Puertos de Altagracia', 1),
        (@PaisVe, N'Punceres', 1),
        (@PaisVe, N'Punta Cardón', 1),
        (@PaisVe, N'Punta Gorda', 1),
        (@PaisVe, N'Punta de Mata', 1),
        (@PaisVe, N'Punta de Piedras', 1),
        (@PaisVe, N'Punto Fijo', 1),
        (@PaisVe, N'Páez', 1),
        (@PaisVe, N'Píritu', 1),
        (@PaisVe, N'Píritu Falcón', 1),
        (@PaisVe, N'Píritu de Portuguesa', 1),
        (@PaisVe, N'Queniquea', 1),
        (@PaisVe, N'Quiriquire', 1),
        (@PaisVe, N'Quíbor', 1),
        (@PaisVe, N'Rafael Rangel', 1),
        (@PaisVe, N'Rafael Urdaneta', 1),
        (@PaisVe, N'Rangel', 1),
        (@PaisVe, N'Ribero', 1),
        (@PaisVe, N'Ricaurte', 1),
        (@PaisVe, N'Rivas Dávila', 1),
        (@PaisVe, N'Rojas', 1),
        (@PaisVe, N'Rosario de Perijá', 1),
        (@PaisVe, N'Roscio', 1),
        (@PaisVe, N'Rubio', 1),
        (@PaisVe, N'Río Caribe', 1),
        (@PaisVe, N'Río Chico', 1),
        (@PaisVe, N'Río Claro', 1),
        (@PaisVe, N'Río Negro', 1),
        (@PaisVe, N'Rómulo Gallegos', 1),
        (@PaisVe, N'Sabana de Mendoza', 1),
        (@PaisVe, N'Sabana de Parra', 1),
        (@PaisVe, N'Sabana de Uchire', 1),
        (@PaisVe, N'Sabaneta', 1),
        (@PaisVe, N'Sabaneta de Palma', 1),
        (@PaisVe, N'Salom', 1),
        (@PaisVe, N'Samancito', 1),
        (@PaisVe, N'Samuel Darío Maldonado', 1),
        (@PaisVe, N'San Antonio de Los Altos', 1),
        (@PaisVe, N'San Antonio de Maturín', 1),
        (@PaisVe, N'San Antonio del Golfo', 1),
        (@PaisVe, N'San Antonio del Tachira', 1),
        (@PaisVe, N'San Carlos', 1),
        (@PaisVe, N'San Casimiro', 1),
        (@PaisVe, N'San Cristóbal', 1),
        (@PaisVe, N'San Diego', 1),
        (@PaisVe, N'San Diego de Los Altos', 1),
        (@PaisVe, N'San Felipe', 1),
        (@PaisVe, N'San Fernando', 1),
        (@PaisVe, N'San Fernando de Apure', 1),
        (@PaisVe, N'San Fernando de Atabapo', 1),
        (@PaisVe, N'San Fernando del Guapo', 1),
        (@PaisVe, N'San Francisco', 1),
        (@PaisVe, N'San Francisco de Macanao', 1),
        (@PaisVe, N'San Francisco de Yare', 1),
        (@PaisVe, N'San Félix', 1),
        (@PaisVe, N'San Genaro de Boconoíto', 1),
        (@PaisVe, N'San Gerónimo de Guayabal', 1),
        (@PaisVe, N'San Joaquín', 1),
        (@PaisVe, N'San Josecito', 1),
        (@PaisVe, N'San José de Aerocuar', 1),
        (@PaisVe, N'San José de Bolívar', 1),
        (@PaisVe, N'San José de Guanipa', 1),
        (@PaisVe, N'San José de Guaribe', 1),
        (@PaisVe, N'San José de Los Altos', 1),
        (@PaisVe, N'San José de Perijá', 1),
        (@PaisVe, N'San José de Río Chico', 1),
        (@PaisVe, N'San Juan Bautista', 1),
        (@PaisVe, N'San Juan de Capistrano', 1),
        (@PaisVe, N'San Juan de Los Cayos', 1),
        (@PaisVe, N'San Juan de Los Morros', 1),
        (@PaisVe, N'San Juan de Payara', 1),
        (@PaisVe, N'San Judas Tadeo', 1),
        (@PaisVe, N'San Luis', 1),
        (@PaisVe, N'San Lázaro', 1),
        (@PaisVe, N'San Mateo', 1),
        (@PaisVe, N'San Mateo Anzoátegui', 1),
        (@PaisVe, N'San Pablo Anzoátegui', 1),
        (@PaisVe, N'San Pablo de Yaracuy', 1),
        (@PaisVe, N'San Pedro de Coche', 1),
        (@PaisVe, N'San Pedro de Los Altos', 1),
        (@PaisVe, N'San Pedro del Río', 1),
        (@PaisVe, N'San Rafael de Carvajal', 1),
        (@PaisVe, N'San Rafael de Laya', 1),
        (@PaisVe, N'San Rafael de Onoto', 1),
        (@PaisVe, N'San Rafael del Moján', 1),
        (@PaisVe, N'San Sebastián', 1),
        (@PaisVe, N'San Timoteo', 1),
        (@PaisVe, N'San Tomé', 1),
        (@PaisVe, N'San Vicente Monagas', 1),
        (@PaisVe, N'San Vicente de Sucre', 1),
        (@PaisVe, N'Sanare', 1),
        (@PaisVe, N'Santa Ana', 1),
        (@PaisVe, N'Santa Ana Falcón', 1),
        (@PaisVe, N'Santa Ana Táchira', 1),
        (@PaisVe, N'Santa Ana de Anzoátegui', 1),
        (@PaisVe, N'Santa Ana de Nueva Esparta', 1),
        (@PaisVe, N'Santa Ana de Trujillo', 1),
        (@PaisVe, N'Santa Bárbara', 1),
        (@PaisVe, N'Santa Bárbara de Barinas', 1),
        (@PaisVe, N'Santa Bárbara del Zulia', 1),
        (@PaisVe, N'Santa Cruz de Aragua', 1),
        (@PaisVe, N'Santa Cruz de Bucaral', 1),
        (@PaisVe, N'Santa Cruz de Mara', 1),
        (@PaisVe, N'Santa Cruz de Mora', 1),
        (@PaisVe, N'Santa Cruz del Zulia', 1),
        (@PaisVe, N'Santa Elena de Arenales', 1),
        (@PaisVe, N'Santa Elena de Uairén', 1),
        (@PaisVe, N'Santa Fe Anzoátegui', 1),
        (@PaisVe, N'Santa Fe de Sucre', 1),
        (@PaisVe, N'Santa Inés', 1),
        (@PaisVe, N'Santa Lucía', 1),
        (@PaisVe, N'Santa María de Ipire', 1),
        (@PaisVe, N'Santa Rita', 1),
        (@PaisVe, N'Santa Rosa', 1),
        (@PaisVe, N'Santa Rosalía', 1),
        (@PaisVe, N'Santa Teresa', 1),
        (@PaisVe, N'Santiago Mariño', 1),
        (@PaisVe, N'Santo Domingo', 1),
        (@PaisVe, N'Santos Marquina', 1),
        (@PaisVe, N'Santos Michelena', 1),
        (@PaisVe, N'Sarare', 1),
        (@PaisVe, N'Sebastián Francisco de Miranda', 1),
        (@PaisVe, N'Seboruco', 1),
        (@PaisVe, N'Sifontes', 1),
        (@PaisVe, N'Simón Bolívar', 1),
        (@PaisVe, N'Simón Planas', 1),
        (@PaisVe, N'Simón Rodríguez', 1),
        (@PaisVe, N'Sinamaica', 1),
        (@PaisVe, N'Siquisique', 1),
        (@PaisVe, N'Socopó', 1),
        (@PaisVe, N'Soledad', 1),
        (@PaisVe, N'Sosa', 1),
        (@PaisVe, N'Sotillo', 1),
        (@PaisVe, N'Sucre', 1),
        (@PaisVe, N'Tabáy', 1),
        (@PaisVe, N'Tacarigua de La Laguna', 1),
        (@PaisVe, N'Tacarigua de Mamporal', 1),
        (@PaisVe, N'Tamare', 1),
        (@PaisVe, N'Temblador', 1),
        (@PaisVe, N'Teresen', 1),
        (@PaisVe, N'Timotes', 1),
        (@PaisVe, N'Tinaco', 1),
        (@PaisVe, N'Tinaquillo', 1),
        (@PaisVe, N'Tintorero', 1),
        (@PaisVe, N'Tocopero', 1),
        (@PaisVe, N'Tocorón', 1),
        (@PaisVe, N'Tocuyito', 1),
        (@PaisVe, N'Tocuyo de La Costa', 1),
        (@PaisVe, N'Tocópero', 1),
        (@PaisVe, N'Torbes', 1),
        (@PaisVe, N'Torondoy', 1),
        (@PaisVe, N'Torres', 1),
        (@PaisVe, N'Tostós', 1),
        (@PaisVe, N'Tovar', 1),
        (@PaisVe, N'Trujillo', 1),
        (@PaisVe, N'Tubores', 1),
        (@PaisVe, N'Tucacas', 1),
        (@PaisVe, N'Tucani', 1),
        (@PaisVe, N'Tucupido', 1),
        (@PaisVe, N'Tucupita', 1),
        (@PaisVe, N'Tulio Febres Cordero', 1),
        (@PaisVe, N'Tumeremo', 1),
        (@PaisVe, N'Tunapuy', 1),
        (@PaisVe, N'Turmero', 1),
        (@PaisVe, N'Turumo', 1),
        (@PaisVe, N'Turén', 1),
        (@PaisVe, N'Tácata', 1),
        (@PaisVe, N'Táriba', 1),
        (@PaisVe, N'Tía Juana', 1),
        (@PaisVe, N'Umuquena', 1),
        (@PaisVe, N'Unare', 1),
        (@PaisVe, N'Unión', 1),
        (@PaisVe, N'Upata', 1),
        (@PaisVe, N'Urachiche', 1),
        (@PaisVe, N'Uracoa', 1),
        (@PaisVe, N'Urama', 1),
        (@PaisVe, N'Urdaneta', 1),
        (@PaisVe, N'Ureña', 1),
        (@PaisVe, N'Uribante', 1),
        (@PaisVe, N'Urica', 1),
        (@PaisVe, N'Urumaco', 1),
        (@PaisVe, N'Valdéz', 1),
        (@PaisVe, N'Valencia', 1),
        (@PaisVe, N'Valera', 1),
        (@PaisVe, N'Valle de Guanape', 1),
        (@PaisVe, N'Valle de La Pascua', 1),
        (@PaisVe, N'Vallecito', 1),
        (@PaisVe, N'Valmore Rodríguez', 1),
        (@PaisVe, N'Vargas', 1),
        (@PaisVe, N'Vigirimita', 1),
        (@PaisVe, N'Villa Rosa', 1),
        (@PaisVe, N'Villa de Cura', 1),
        (@PaisVe, N'Villa del Rosario', 1),
        (@PaisVe, N'Villalba', 1),
        (@PaisVe, N'Yaguaraparo', 1),
        (@PaisVe, N'Yaracal', 1),
        (@PaisVe, N'Yaritagua', 1),
        (@PaisVe, N'Yoco', 1),
        (@PaisVe, N'Yumare', 1),
        (@PaisVe, N'Zamora', 1),
        (@PaisVe, N'Zaraza', 1),
        (@PaisVe, N'Zea', 1),
        (@PaisVe, N'Zuata', 1)
;
END
GO

SELECT (SELECT COUNT(*) FROM Pais) TotalPaises, (SELECT COUNT(*) FROM Ciudad WHERE PaisId=(SELECT PaisId FROM Pais WHERE Codigo=N'VE')) CiudadesVE;
SELECT TOP 5 Codigo, Nombre, Moneda FROM Pais WHERE Codigo IN (N'CO',N'VE',N'PE',N'EC',N'MX');
PRINT N'30_AjustePaisesCiudadMonedaUtf8 aplicado.';
GO